import streamlit as st
import google.generativeai as genai
from PIL import Image
import json
import re

# --- 1. CONFIGURATION ---
try:
    API_KEY = st.secrets["GEMINI_API_KEY"]
except:
    # Local fallback for VS Code testing
    API_KEY = genai.configure(api_key=API_KEY)

genai.configure(api_key=API_KEY)
model = genai.GenerativeModel('gemini-3-flash-preview')

# --- 2. PAGE CONFIG ---
st.set_page_config(page_title="SafetySense AI", page_icon="🛡️", layout="wide")

# Sidebar
st.sidebar.title("🛠️ Developer Info")
st.sidebar.write("**Name:** Rushikesh Naik")
st.sidebar.write("**Role:** Data Analyst / AI Developer")
st.sidebar.divider()
st.sidebar.info("This tool uses Gemini 3 Flash to audit industrial safety compliance via Computer Vision.")

# --- 3. UI LAYOUT ---
st.title("🛡️ SafetySense AI Auditor")
st.write("Professional Site Compliance Dashboard")
st.write("---")

col1, col2 = st.columns([1, 1])

with col1:
    st.markdown("### 📷 Site Image")
    uploaded_file = st.file_uploader("Upload worksite photo...", type=["jpg", "jpeg", "png"])
    if uploaded_file:
        img = Image.open(uploaded_file)
        st.image(img, caption='Uploaded Image', use_container_width=True)

with col2:
    st.markdown("### 📝 Audit Report")
    if uploaded_file:
        if st.button("🚀 Run Safety Audit"):
            with st.spinner('AI Inspector is analyzing the site...'):
                try:
                    prompt = """
                    Analyze this image for industrial safety compliance. 
                    Check for PPE (Helmets, Vests, Gloves) and Hazards.
                    Return ONLY a JSON object:
                    {"status": "Safe" or "Violation", "score": 1-10, "finding": "detailed description"}
                    """
                    response = model.generate_content([prompt, img])
                    
                    # Parsing JSON
                    clean_json = re.search(r'\{.*\}', response.text, re.DOTALL)
                    if clean_json:
                        result = json.loads(clean_json.group())
                        
                        # Display Metrics
                        if result['status'] == "Safe":
                            st.success(f"✅ STATUS: {result['status']}")
                        else:
                            st.error(f"⚠️ STATUS: {result['status']}")
                        
                        st.metric("Compliance Score", f"{result['score']}/10")
                        st.write(f"**Detailed Finding:** {result['finding']}")
                        
                        # --- DOWNLOAD BUTTON ---
                        st.divider()
                        report_text = f"""SAFETY AUDIT REPORT
-------------------
Status: {result['status']}
Score: {result['score']}/10
Timestamp: 2026-02-25
-------------------
Findings:
{result['finding']}
-------------------
Generated by SafetySense AI (Developer: Rushikesh Naik)
"""
                        st.download_button(
                            label="📥 Download Audit Report",
                            data=report_text,
                            file_name=f"Safety_Audit_{result['status']}.txt",
                            mime="text/plain"
                        )
                    else:
                        st.write(response.text)
                except Exception as e:
                    st.error(f"Error: {e}")
    else:
        st.info("Please upload an image to generate a report.")
